### ISSUE TITLE
Add latex-emoji to l3prefixes

### ISSUE THREAD

**Issue by pablgonz** [stone-zeng/latex-emoji#1]
Hi, could you add your packages to  latex3/l3kernel/doc/l3prefixes.csv.
Here's a link:

https://github.com/latex3/latex3/blob/master/l3kernel/doc/l3prefixes.csv

That file is for contact info, but also to keep track of the registered prefixes in packages to avoid that two packages use the same prefix and clash.

Thank you so much for this package , they're great :)
Greetings
Pablo

**Comment by stone-zeng** [comment]
See <https://github.com/latex3/latex3/pull/686>. Thank you!
