### ISSUE TITLE
"Can't find emoji" error when using two chapters

### ISSUE THREAD

**Issue by cnngimenez** [stone-zeng/latex-emoji#10]
Hi!  👋🏽 
I found this strange bug when using emojis on chapters. For example:

```latex
\documentclass{book}
\usepackage{fontspec}
\usepackage{emoji}
\begin{document}
\chapter{\emoji{thumbs-up} Test1}
\chapter{Test2}
\chapter{Test3}
\end{document}
```

When compiling with LuaLaTex 1.13.0 (or using LuaLaTeX 2021 in Overleaf) I get a proper PDF, but the compiler shows the following error:

```
./chapter-emoji.tex:12: Package emoji Error: The emoji name "THUMBS-UP" can't be found.
(emoji)                Please check your spelling or try another one.

Type <return> to continue.
 ...                                              
                                                  
l.12 \chapter
           {Test2}
```

But, when I delete `\chapter{Test2}` and `\chapter{Test3}` LuaLaTeX compiles without errors. The same problem happens at Overleaf (see [this project](https://www.overleaf.com/read/gjsnbmzwrbtf)). 

I attach my log file: [chapter-emoji.log](https://github.com/stone-zeng/latex-emoji/files/7514695/chapter-emoji.log). Also, you can download all output files at the Overleaf page.

Is there a way to repair the error? 

Cheers!

**Comment by stone-zeng** [comment]
That's because the text in `\chapter{...}` will be capitalized in the header, even the argument of macros. You can use

```tex
\chapter{\MakeLowercase{\emoji{thumbs-up}} Test}
```

or define a (protected) macro:

```tex
\DeclareRobustCommand\thumbsup{\emoji{thumbs-up}}  % Make it protected
\chapter{\thumbsup{} Test1}
```

**Comment by cnngimenez** [comment]
Thanks! it was definitely that! 
The problem can be fixed with both: the `\MakeLowercase` or the protected macro!
