### ISSUE TITLE
Emojis are not usable in overlay-aware slides (beamer)

### ISSUE THREAD

**Issue by amyspark** [stone-zeng/latex-emoji#12]
👋 

Would it be possible to implement beamer-aware emojis? Currently this example results in a floating drop of blood where the second (transparent) line is:

```tex
\documentclass{beamer}
\usepackage{emoji}
\setbeamercovered{transparent=0}
\begin{document}
\begin{frame}{Test}
\begin{itemize}[<+->]
\item This will appear on the first slide.
\item This will appear on the second slide. \emoji{drop-of-blood}
\end{itemize}
\end{frame}
\end{document}
```

| First | Second |
| ------------- | ------------- |
| ![test-1](https://user-images.githubusercontent.com/13498015/161407090-261e6c54-00c2-4938-9356-9ec2efc0a200.png)  | ![test-2](https://user-images.githubusercontent.com/13498015/161407093-880057eb-87f8-4e1f-b528-6f1ff66b9efe.png)  |

**Comment by stone-zeng** [comment]
I think this issue is more likely to be related to beamer and I have created a new issue there: https://github.com/josephwright/beamer/issues/769.
