### ISSUE TITLE
Pinata emoji not working

### ISSUE THREAD

**Issue by hunter1749** [stone-zeng/latex-emoji#13]
`\emoji{pinata}` appears as a box instead of a pinata emoji. Using default setting, nothing added, only the emoji command.
```latex
\documentclass{standalone}

\usepackage{emoji}

\begin{document}

	adasdasd
	dasds
	\emoji{black-square-button}
	\emoji{pinata}
	sadsd
	asdasd
	
\end{document}
```
[The result](https://i.imgur.com/uhQseVU.png).

I think Segoe UI Emoji is my default font because I'm on Windows, but I will try with the font used in documentation you have made.

Adding `\setemojifont{Twitter Color Emoji}` or `\setemojifont{Twitter Color Emoji SVGinOT}` helps, but they're all black and white. I followed [this](https://github.com/13rac1/twemoji-color-font#install-on-windows) installation guide.

I have uninstalled Twitter Color Emoji now, and it's all black and white even with no `\setemojifont` command. How do I get back the coloured font I had before? I can't find Segoe UI Emoji anywhere to download, and I've gone through the provided uninstall script multiple times.

I've settled on `\setemojifont{TwemojiMozilla}`, but I'd still like to have the other Twitter's emojis working and have back the default font to Segoe UI Emoji with **coloured** emojis, because they're stuck at black and white now.

Also in my fonts, everything appears in colour as it should, the Twitter Emoji font did, and the Segoe UI Emoji still is, although in the document they both appear black and white, only outlines are there, sort of like this if it can be seen 🪅. Same with Mozilla font, but that one also appears in colour in the document as it should.

I see that it's only outlines even in the browser now, how do I revert back to default Segoe UI Emoji font???

I got it working in the browser and the documents again by multiple restarts and changing the [uninstall script](https://github.com/13rac1/twemoji-color-font/blob/main/windows/uninstall.cmd) so that it starts using the fonts in `C:\...\Fonts` folder again, not `C:\...\Roaming\Fonts` as I assume the script does it. I also deleted the ones that I was able to from the latter, probably duplicates from previous uninstall attempts, for some reason Twitter fonts were still in there too. I guess I'll stick with Mozilla font, I just can't get the Twitter Emoji font working, I guess they're pretty similar.

**Comment by Ar-Kan** [comment]
Twitter Color Emoji fallback to B&W when [SVG font support is lacking](https://github.com/13rac1/twemoji-color-font/issues/79) 🤷, this is independent of the this package .

As for Segoe UI Emoji is copyrighted by Microsoft, so it wont be officially available for download (btw, on Windows, the fonts are located at `C:\Windows\Fonts`).

Finally, the `\setemoji` command is a wrapper around `\setfontface` from fontspec package, so you can pass additional parameters. For example, the relative path of the font file, like this `\setemojifont{FontFile.ttf}[Path=path/to/the/font]`.

**Comment by hunter1749** [comment]
Thanks for the insight and a reminder to close this issue 👍
