### ISSUE TITLE
Conflict with packages that load fontspec

### ISSUE THREAD

**Issue by mdelhoneux** [stone-zeng/latex-emoji#14]
If I use a package that loads fontspec (e.g. pxfonts or newpxtext) in combination with the emoji package, I get the following error: `Package fontspec Error: The font "NotoColorEmoji" cannot be found.`

**Comment by stone-zeng** [comment]
Can you provide a complete (but minimal) `.tex` source file to show this issue?

**Comment by mdelhoneux** [comment]
Sure, here:
```
\documentclass{article}
\usepackage{newpxtext} 
\usepackage{emoji}

\begin{document}
    \emoji{thinking-face}
\end{document}
```

**Comment by Ar-Kan** [comment]
This package does not ship with fonts, did you load them 🫣?

https://pt.overleaf.com/read/tftgbqcqpryk#e75c47

**Comment by stone-zeng** [comment]
It seems that you should install the emoji font (e.g. `noto-emoji` package) or explicitly set the font using `\setemojifont`.

**Comment by mdelhoneux** [comment]
That doesn't explain the issue above at all, where the example does work without the `\usepackage{newpxtext}` line

**Comment by Ar-Kan** [comment]
But it works with/without `newpxtext` package, as you can see on this project: https://pt.overleaf.com/read/kctxbrtrhfhw#33b4ac
Besides, the provided error is thrown by `fontspec` not this package.
