### ISSUE TITLE
Which fonts support all the emoji symbols?

### ISSUE THREAD

**Issue by aihuawu** [stone-zeng/latex-emoji#3]
Thank Stone for this wonderful package.
I have printed your document.
I am using texlive 2020, font noto family.
My ubuntu 2020.04

Still I find a few symbols are just blank box, or separated symbols.
I believe the noto fonts do not fully support all the symbols.
I have access to windows and I can copy windows fonts to ubuntu.
Can you suggest any fonts so that I can use all the emoji symbols?

Thank you once again!

George Wu

**Comment by aihuawu** [comment]
I have tried the 3 fonts, E13.0 emoji are white box.

% \setemojifont{Twemoji Mozilla}
% \setemojifont{Noto Color Emoji}
\setemojifont{Segoe UI Emoji}

**Comment by aihuawu** [comment]
The E12.1
One char is displayed with 2 or 3 separate chars.

**Comment by stone-zeng** [comment]
For **Unicode 12.1 (E12.1)**: Apple Color Emoji and JoyPixels support it. Twemoji Mozilla already support it too, and I will update this font in TeX distribution, as well as the document.

For **Unicode 13.0 (E13.0)**: You may try [JoyPixels](https://www.joypixels.com/fonts). Twemoji has already releases the new version too, but the `COLR/CPAL` version (Twemoji Mozilla) hasn't been synchronized with it. Apple and Google Noto hopefully will update their emoji fonts in later this year.
