### ISSUE TITLE
loca table not found 

### ISSUE THREAD

**Issue by FabianGD** [stone-zeng/latex-emoji#6]
Hi there,

thanks a lot for your great package! I'd really like to use it on Linux. Unfotunately, I can't get the package to work. As soon as I use a color emoji font (such as NotoColorEmoji), compilation of the following MWE will crash with the following output:

```latex
\documentclass[a4paper]{article}

\usepackage{emoji}
\setemojifont{NotoColorEmoji.ttf}[Path=./]

\begin{document}

\emoji{grin}

\end{document}
```

```
</usr/share/fonts/texlive-lm/lmroman10-regular.otf><./NotoColorEmoji.ttf
! error:  (file ./NotoColorEmoji.ttf) (ttf): loca table not found
!  ==> Fatal error occurred, no output PDF file produced!
```

Can you help me with that? I tried other emoji fonts already, but for some reason, it will always fail on me.

EDIT: I tried with both TeXLive 2020 and TeXLive 2019 (and `lualatex-dev`)

**Comment by stone-zeng** [comment]
You may try to update TeX Live to the latest version, and if it doesn't work please upload a complete compile log file.

**Comment by FabianGD** [comment]
Ok, I switched to the texlive/texlive docker image for compilation, and that did the trick. :tada: 

I had used the TL versions from the Ubuntu / openSUSE repos before, which was probably a bad idea. 

Thanks a lot again, the package really works like a charm now. :grinning:
