### ISSUE TITLE
Can this work with `dvilualatex`?

### ISSUE THREAD

**Issue by cshaa** [stone-zeng/latex-emoji#9]
## Motivation
I want to use the emojis in math equations in [Manim](https://www.manim.community/). When using TeX code in Manim, it uses `dvilualatex` in the background to compile TeX to DVI. Then it uses `dvisvgm` to convert DVI to SVG, which is the format it needs.

## Problem
Using `dvilualatex` to compile this simple TEX file
```latex
\documentclass[preview]{standalone}
\usepackage{emoji}
\begin{document}
\emoji{pineapple}
\end{document}
```
results in a faulty DVI file. Specifically, there's a broken reference to a font:
```
WARNING: font file 'NotoColorEmoji:mode=harf;script=DFLT;language=dflt;.mf' not found
processing page 1
```
Is there any walkaround for this?

## System Info
 * elementary 6, based on Ubuntu 20.04.3 LTS
 * texlive 2021
 * emoji.sty version 0.2.2
 * dvilualatex 1.13.2

**Comment by stone-zeng** [comment]
It seems `dvisvgm` doesn't support embedding emoji fonts currently, see https://github.com/mgieseki/dvisvgm/issues/162.
